# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-en8RxmdG3LvnJ7GcEQhQhpDIttmdue
"""

score = input().split()

fail = 0

for i in score:
  if int(i)<60:
    fail = fail+1

print(fail)